version: "3"

services:
  flask:
    build: .
    container_name: stock-projection-service
    restart: on-failure
    ports:
      - "5000:5000"
    networks:
      - stocknet
    environment:
      - FLASK_ENV=development
      - WEB_CONCURRENCY=3
      - MONGODB_DATABASE=stock-db
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: stock-projection-db
    restart: always
    command: mongod --auth
    ports:
      - "27017:27017"
    networks:
      - stocknet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=stock-db
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  stocknet:
    driver: bridge
